name: Deploy Ultroid

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Verificar archivos clonados
        run: ls -R  # Verifica la estructura de archivos en el repositorio

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y redis-server
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Iniciar Redis
        run: sudo redis-server &  # Inicia Redis en segundo plano

      - name: Cargar variables de entorno desde .env
        run: |
          cp .env.example .env  # Asegúrate de tener un .env.example como base
          export $(grep -v '^#' .env | xargs)

      - name: Dar permisos de ejecución a startup
        run: chmod +x ./startup  # Cambia la ruta si está en otro lugar

      - name: Ejecutar script de inicio
        run: bash ./startup  # Se ejecuta usando las variables de .env