name: Deploy Ultroid

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Verificar archivos clonados
        run: |
          ls -R  # Verifica la estructura de archivos en el repositorio

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y redis-server
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Iniciar Redis
        run: |
          sudo redis-server &  # Inicia Redis en segundo plano

      - name: Dar permisos de ejecución a startup
        run: chmod +x ./startup  # Cambia la ruta para apuntar al archivo en la raíz

      - name: Ejecutar script de inicio
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION: ${{ secrets.SESSION }}
          REDIS_URI: ${{ secrets.REDIS_URI }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Aquí agregamos el bot_token
        run: |
          bash ./startup  # Aquí apuntamos al archivo en la raíz